### ISSUE TITLE
DNAD

### ISSUE THREAD

**Issue by stumarcus314** [jacobwilliams/NumDiff#5]
As an alternative to finite-differences, dual numbers can be used to compute the Jacobians without error (up to machine precision).

https://www.sciencedirect.com/science/article/pii/S0010465513000027 
https://github.com/joddlehod/dnad/blob/master/dnad.F90

**Comment by jacobwilliams** [comment]
Agreed. Finite diffs are still good for:
* If your function has black-box components.
* If your function is already coded up using real variables and you can't change it (or it's too much work to change it).
* Checking the derivatives of other methods
